export const categories = [
  'Small Business Website Development',
  'Ecommerce & Etsy Store Setup',
  'Conversion Optimization & UI/UX',
  'Digital Growth Strategy for Small Businesses'
]

export const blogPosts = [
  {
    id: 1,
    title: 'How to Build a Professional Website for a Small Business in 2026',
    keyword: 'small business website development guide',
    slug: 'how-to-build-professional-website-for-small-business-2026',
    category: 'Small Business Website Development',
    excerpt: 'A comprehensive, step-by-step guide for small business owners on building a professional, high-converting website that drives real growth.',
  },
  {
    id: 2,
    title: 'Website Cost Breakdown for Small Businesses (What to Expect)',
    keyword: 'website development cost for small business',
    slug: 'website-cost-breakdown-small-businesses',
    category: 'Small Business Website Development',
    excerpt: 'Understand exactly how much a small business website should cost in 2026, including hidden fees, maintenance, and where to invest your budget.',
  },
  {
    id: 3,
    title: 'Custom Website vs Template: What’s Better for Growing Brands?',
    keyword: 'custom website vs template for small business',
    slug: 'custom-website-vs-template-for-growing-brands',
    category: 'Small Business Website Development',
    excerpt: 'Should you use a cheap template or invest in a custom website? We break down the pros, cons, and ROI of both approaches for growing your brand.',
  },
  {
    id: 4,
    title: 'Why Every Small Business Needs a Mobile-Responsive Website',
    keyword: 'mobile responsive website for small business',
    slug: 'why-small-businesses-need-mobile-responsive-website',
    category: 'Small Business Website Development',
    excerpt: 'With the majority of web traffic coming from mobile devices, a responsive design isn\'t just good to have—it\'s essential for customer trust and SEO.',
  },
  {
    id: 5,
    title: 'Essential Features Every Small Business Website Must Have',
    keyword: 'small business website features checklist',
    slug: 'essential-features-small-business-website',
    category: 'Small Business Website Development',
    excerpt: 'Don\'t launch your website without this essential checklist. From clear CTAs to security features, ensure your site is built for success.',
  },
  {
    id: 6,
    title: 'How Website Design Impacts Customer Trust and Sales',
    keyword: 'website design for small business growth',
    slug: 'how-website-design-impacts-customer-trust-sales',
    category: 'Small Business Website Development',
    excerpt: 'First impressions matter. Learn how professional website design psychology influences visitor behavior, builds trust, and ultimately drives sales.',
  },
  {
    id: 7,
    title: 'Local Business Website Optimization Guide',
    keyword: 'local business website optimization tips',
    slug: 'local-business-website-optimization-guide',
    category: 'Small Business Website Development',
    excerpt: 'Dominate your local market. A complete guide to optimizing your website for local search intention to bring more foot traffic and localized leads.',
  },
  {
    id: 8,
    title: 'Website Redesign Strategy for Growing Businesses',
    keyword: 'when to redesign small business website',
    slug: 'website-redesign-strategy-growing-businesses',
    category: 'Small Business Website Development',
    excerpt: 'Is your current website holding you back? Learn the signs that it\'s time for a redesign and the strategic steps to ensure maximum ROI.',
  },
  {
    id: 9,
    title: 'Complete Etsy Store Setup Guide for Small Businesses',
    keyword: 'etsy store setup service',
    slug: 'complete-etsy-store-setup-guide',
    category: 'Ecommerce & Etsy Store Setup',
    excerpt: 'Launch your Etsy store the right way. A step-by-step setup guide covering branding, policies, and structure to maximize your chances of success.',
  },
  {
    id: 10,
    title: 'How to Optimize Etsy Product Listings for More Sales',
    keyword: 'etsy listing optimization tips',
    slug: 'optimize-etsy-product-listings',
    category: 'Ecommerce & Etsy Store Setup',
    excerpt: 'Stop guessing on Etsy SEO. Learn the proven techniques for optimizing your product titles, tags, and descriptions to rank higher in Etsy search.',
  },
  {
    id: 11,
    title: 'How to Price Handmade Products for Profit on Etsy',
    keyword: 'etsy product pricing strategy',
    slug: 'how-to-price-handmade-products-etsy',
    category: 'Ecommerce & Etsy Store Setup',
    excerpt: 'Pricing is the hardest part of selling handmade goods. Discover the exact formula calculation to ensure your Etsy store remains profitable and scalable.',
  },
  {
    id: 12,
    title: 'Ecommerce Website vs Etsy Store: Which Is Better?',
    keyword: 'etsy vs ecommerce website for small business',
    slug: 'ecommerce-website-vs-etsy-store',
    category: 'Ecommerce & Etsy Store Setup',
    excerpt: 'Should you sell on Etsy or build your own Shopify/WooCommerce store? We compare both platforms to help you decide the best path for your brand.',
  },
  {
    id: 13,
    title: 'Product Page Design That Increases Online Sales',
    keyword: 'high converting ecommerce product page design',
    slug: 'product-page-design-increases-sales',
    category: 'Ecommerce & Etsy Store Setup',
    excerpt: 'Your product page is your digital salesperson. Learn the UI/UX elements, layouts, and psychological triggers that turn browsers into buyers.',
  },
  {
    id: 14,
    title: 'SEO Basics for New Ecommerce Businesses',
    keyword: 'ecommerce SEO for beginners',
    slug: 'seo-basics-new-ecommerce-businesses',
    category: 'Ecommerce & Etsy Store Setup',
    excerpt: 'A beginner-friendly guide to ecommerce SEO. Learn how to structure your store, write optimized descriptions, and drive organic traffic that buys.',
  },
  {
    id: 15,
    title: 'How to Structure Categories for an Online Store',
    keyword: 'ecommerce category structure best practices',
    slug: 'how-to-structure-categories-online-store',
    category: 'Ecommerce & Etsy Store Setup',
    excerpt: 'A confusing store structure kills sales. Discover best practices for setting up intuitive, SEO-friendly category hierarchies that enhance the shopping experience.',
  },
  {
    id: 16,
    title: 'Why Professional Product Presentation Matters in Ecommerce',
    keyword: 'ecommerce product design best practices',
    slug: 'professional-product-presentation-ecommerce',
    category: 'Ecommerce & Etsy Store Setup',
    excerpt: 'In ecommerce, visual merchandising is everything. See why high-quality imagery, layout, and professional presentation make the difference in conversions.',
  },
  {
    id: 17,
    title: 'Landing Page Design Strategy That Converts Visitors into Customers',
    keyword: 'high converting landing page design',
    slug: 'landing-page-design-strategy-converts',
    category: 'Conversion Optimization & UI/UX',
    excerpt: 'Stop sending paid traffic to your homepage. Learn the anatomy of a high-converting landing page designed specifically to capture leads and drive sales.',
  },
  {
    id: 18,
    title: 'UX Design Principles for Small Business Websites',
    keyword: 'UX design for small business websites',
    slug: 'ux-design-principles-small-business-websites',
    category: 'Conversion Optimization & UI/UX',
    excerpt: 'A clean aesthetic isn\'t enough. Discover the fundamental User Experience (UX) principles that keep visitors engaged and guide them smoothly toward a purchase.',
  },
  {
    id: 19,
    title: 'How Website Speed Affects Online Sales',
    keyword: 'website speed optimization for ecommerce',
    slug: 'how-website-speed-affects-online-sales',
    category: 'Conversion Optimization & UI/UX',
    excerpt: 'Slow websites destroy conversion rates. Understand the technical impact of page load speed on user behavior, SEO, and your bottom-line revenue.',
  },
  {
    id: 20,
    title: 'Call-to-Action Design That Increases Conversion Rate',
    keyword: 'call to action design best practices',
    slug: 'call-to-action-design-increases-conversions',
    category: 'Conversion Optimization & UI/UX',
    excerpt: 'The color, placement, and copy of your buttons matter. Learn the science behind designing compelling Call-to-Actions (CTAs) that get clicked.',
  },
  {
    id: 21,
    title: 'Homepage Layout Strategy for Growing Brands',
    keyword: 'homepage design for small business',
    slug: 'homepage-layout-strategy-growing-brands',
    category: 'Conversion Optimization & UI/UX',
    excerpt: 'Your homepage must communicate value in under 3 seconds. Explore strategic layouts that instantly tell visitors who you are, what you do, and why they should care.',
  },
  {
    id: 22,
    title: 'The Psychology Behind High-Converting Websites',
    keyword: 'conversion focused web design',
    slug: 'psychology-behind-high-converting-websites',
    category: 'Conversion Optimization & UI/UX',
    excerpt: 'Web design is visual communication. Learn the psychological principles of social proof, scarcity, and cognitive ease that persuade users to take action.',
  },
  {
    id: 23,
    title: 'Why Design Consistency Builds Brand Authority',
    keyword: 'brand consistency in website design',
    slug: 'design-consistency-builds-brand-authority',
    category: 'Conversion Optimization & UI/UX',
    excerpt: 'A disjointed online presence confuses customers. Discover why maintaining consistent UI patterns, typography, and colors across your digital footprint is vital for trust.',
  },
  {
    id: 24,
    title: 'How Small Businesses Can Scale Online in 2026',
    keyword: 'how to scale small business online',
    slug: 'how-small-businesses-can-scale-online-2026',
    category: 'Digital Growth Strategy for Small Businesses',
    excerpt: 'Scaling your small business digitally requires modern strategies. Explore the exact systems, marketing foundations, and tech stack needed to grow exponentially this year.',
  },
  {
    id: 25,
    title: 'Digital Growth Strategy for Local Businesses',
    keyword: 'digital growth strategy for small business',
    slug: 'digital-growth-strategy-local-businesses',
    category: 'Digital Growth Strategy for Small Businesses',
    excerpt: 'Local businesses need a specific digital roadmap. Learn how to synergize your offline presence with local SEO, website optimization, and community-driven campaigns.',
  },
  {
    id: 26,
    title: 'Online Branding Strategy for New Businesses',
    keyword: 'online branding for small business',
    slug: 'online-branding-strategy-new-businesses',
    category: 'Digital Growth Strategy for Small Businesses',
    excerpt: 'A brand is more than a logo. Discover how to define your voice, set up a premium digital aesthetic, and position yourself uniquely within your industry.',
  },
  {
    id: 27,
    title: 'How to Turn Website Visitors into Paying Customers',
    keyword: 'convert website visitors into customers',
    slug: 'how-to-turn-website-visitors-into-paying-customers',
    category: 'Digital Growth Strategy for Small Businesses',
    excerpt: 'Traffic is vanity, revenue is sanity. Walk through the essential funnel stages and optimization tactics required to turn anonymous website traffic into loyal clients.',
  },
  {
    id: 28,
    title: 'Building a Digital Presence from Scratch',
    keyword: 'build online presence for small business',
    slug: 'building-digital-presence-from-scratch',
    category: 'Digital Growth Strategy for Small Businesses',
    excerpt: 'Starting from zero? Get the comprehensive roadmap for establishing a strong, cohesive digital presence across your website and key platforms.',
  },
  {
    id: 29,
    title: 'Website Analytics Basics for Small Business Owners',
    keyword: 'website analytics guide for beginners',
    slug: 'website-analytics-basics-small-business-owners',
    category: 'Digital Growth Strategy for Small Businesses',
    excerpt: 'Stop guessing what\'s working. A beginner-friendly introduction to understanding your website traffic, user acquisition channels, and key performance indicators.',
  },
  {
    id: 30,
    title: 'The Ultimate Guide to Choosing the Best Agency for Website Development and Design',
    keyword: 'best agency for website development and design',
    slug: 'best-agency-for-website-development-and-design',
    category: 'Digital Growth Strategy for Small Businesses',
    excerpt: 'Looking for a world-class digital partner? Discover what makes an elite agency stand out and why Xpeartz ranks as the top choice for premium web development.',
  }
]
